_obj_anim_lib:
		.WORD _obj_anim00
		.WORD _obj_anim01
		.WORD _obj_anim02
		.WORD _obj_anim03
		.WORD _obj_anim04
		.WORD _obj_anim05
		.WORD _obj_anim06
		.WORD _obj_anim07
		.WORD _obj_anim08
		.WORD _obj_anim09
		.WORD _obj_anim0A
		.WORD _obj_anim0B
		.WORD _obj_anim0C
		.WORD _obj_anim0D
		.WORD _obj_anim0E
		.WORD _obj_anim0F
		.WORD _obj_anim10
		.WORD _obj_anim11
		.WORD _obj_anim12
		.WORD _obj_anim13
		.WORD _obj_anim14
		.WORD _obj_anim15
		.WORD _obj_anim16
		.WORD _obj_anim17
		.WORD _obj_anim18
		.WORD _obj_anim19
		.WORD _obj_anim1A
		.WORD _obj_anim1B
		.WORD _obj_anim1C
		.WORD _obj_anim1D
		.WORD _obj_anim1E
		.WORD _obj_anim1F
		.WORD _obj_anim20
		.WORD _obj_anim21
		.WORD _obj_anim22
		.WORD _obj_anim23
		.WORD _obj_anim24
		.WORD _obj_anim25
		.WORD _obj_anim26
		.WORD _obj_anim27
		.WORD _obj_anim28
		.WORD _obj_anim29
		.WORD _obj_anim2A
		.WORD _obj_anim2B
		.WORD _obj_anim2C
		.WORD _obj_anim2D
		.WORD _obj_anim2E
		.WORD _obj_anim2F
		.WORD _obj_anim30
		.WORD _obj_anim31
		.WORD _obj_anim32
		.WORD _obj_anim33
		.WORD _obj_anim34
		.WORD _obj_anim35
		.WORD _obj_anim36
		.WORD _obj_anim37
		.WORD _obj_anim38
		.WORD _obj_anim39
		.WORD _obj_anim3A
		.WORD _obj_anim3B
		.WORD _obj_anim3C
		.WORD _obj_anim3D
		.WORD _obj_anim3E
		.WORD _obj_anim3F
_obj_anim00:
		.WORD _obj_anim00_0
		.WORD _obj_anim00_1
		.WORD _obj_anim00_2
		.WORD _obj_anim00_3
		.WORD _obj_anim00_4
		.WORD _obj_anim00_5
		.WORD _obj_anim00_6
		.WORD _obj_anim00_7
		.WORD _obj_anim00_8
		.WORD _obj_anim00_9
		.WORD _obj_anim00_A
		.WORD _obj_anim00_B
		.WORD _obj_anim00_C
		.WORD _obj_anim00_D
		.WORD _obj_anim00_E
_obj_anim01:
		.WORD _obj_anim01_0
		.WORD _obj_anim01_1
_obj_anim02:
		.WORD _obj_anim02_0
		.WORD _obj_anim02_1
_obj_anim03:
		.WORD _obj_anim03_0
		.WORD _obj_anim03_1
		.WORD _obj_anim03_2
		.WORD _obj_anim03_3
_obj_anim04:
		.WORD _obj_anim04_0
		.WORD _obj_anim04_1
_obj_anim05:
		.WORD _obj_anim05_0
_obj_anim06:
		.WORD _obj_anim06_0
		.WORD _obj_anim06_1
_obj_anim07:
		.WORD _obj_anim07_0
_obj_anim08:
		.WORD _obj_anim08_0
_obj_anim09:
		.WORD _obj_anim09_0
		.WORD _obj_anim09_1
_obj_anim0A:
		.WORD _obj_anim0A_0
_obj_anim0B:
		.WORD _obj_anim0B_0
_obj_anim0C:
		.WORD _obj_anim0C_0
		.WORD _obj_anim0C_1
_obj_anim0D:
		.WORD _obj_anim0D_0
_obj_anim0E:
		.WORD _obj_anim0E_0
_obj_anim0F:
		.WORD _obj_anim0F_0
_obj_anim10:
		.WORD _obj_anim10_0
		.WORD _obj_anim10_1
_obj_anim11:
		.WORD _obj_anim11_0
_obj_anim12:
		.WORD _obj_anim12_0
		.WORD _obj_anim12_1
_obj_anim13:
		.WORD _obj_anim13_0
		.WORD _obj_anim13_1
_obj_anim14:
		.WORD _obj_anim14_1
_obj_anim15:
		.WORD _obj_anim15_0
_obj_anim16:
		.WORD _obj_anim16_0
		.WORD _obj_anim16_1
		.WORD _obj_anim16_2
		.WORD _obj_anim16_3
		.WORD _obj_anim16_4
		.WORD _obj_anim16_5
_obj_anim17:
		.WORD _obj_anim17_0
		.WORD _obj_anim17_1
		.WORD _obj_anim17_2
_obj_anim18:
		.WORD _obj_anim18_0
		.WORD _obj_anim18_1
		.WORD _obj_anim18_2
_obj_anim19:
		.WORD _obj_anim19_0
		.WORD _obj_anim19_1
_obj_anim1A:
		.WORD _obj_anim1A_0
		.WORD _obj_anim1A_1
_obj_anim1B:
		.WORD _obj_anim1B_0
_obj_anim1C:
		.WORD _obj_anim1C_0
		.WORD _obj_anim1C_1
		.WORD _obj_anim1C_2
		.WORD _obj_anim1C_3
		.WORD _obj_anim1C_4
_obj_anim1D:
		.WORD _obj_anim1C_0
		.WORD _obj_anim1C_1
		.WORD _obj_anim1C_2
		.WORD _obj_anim1C_3
		.WORD _obj_anim1D_4
_obj_anim1E:
		.WORD _obj_anim1C_0
		.WORD _obj_anim1C_1
		.WORD _obj_anim1C_2
		.WORD _obj_anim1C_3
		.WORD _obj_anim1E_4
_obj_anim1F:
		.WORD _obj_anim1C_0
		.WORD _obj_anim1C_1
		.WORD _obj_anim1C_2
		.WORD _obj_anim1C_3
		.WORD _obj_anim1F_4
_obj_anim20:
		.WORD _obj_anim20_0
		.WORD _obj_anim20_1
_obj_anim21:
		.WORD _obj_anim21_0
		.WORD _obj_anim21_1
		.WORD _obj_anim21_2
		.WORD _obj_anim21_3
		.WORD _obj_anim21_4
_obj_anim22:
		.WORD _obj_anim21_0
		.WORD _obj_anim21_1
		.WORD _obj_anim21_2
		.WORD _obj_anim21_3
		.WORD _obj_anim22_4
_obj_anim23:
		.WORD _obj_anim23_0
		.WORD _obj_anim23_1
		.WORD _obj_anim23_2
		.WORD _obj_anim23_3
		.WORD _obj_anim23_4
_obj_anim24:
		.WORD _obj_anim23_0
		.WORD _obj_anim23_1
		.WORD _obj_anim23_2
		.WORD _obj_anim23_3
		.WORD _obj_anim24_4
_obj_anim25:
		.WORD _obj_anim23_0
		.WORD _obj_anim23_1
		.WORD _obj_anim23_2
		.WORD _obj_anim23_3
		.WORD _obj_anim25_4
_obj_anim26:
		.WORD _obj_anim23_0
		.WORD _obj_anim23_1
		.WORD _obj_anim23_2
		.WORD _obj_anim23_3
		.WORD _obj_anim26_4
_obj_anim27:
		.WORD _obj_anim23_0
		.WORD _obj_anim23_1
		.WORD _obj_anim23_2
		.WORD _obj_anim23_3
		.WORD _obj_anim27_4
_obj_anim28:
		.WORD _obj_anim28_0
		.WORD _obj_anim28_1
		.WORD _obj_anim28_2
		.WORD _obj_anim28_3
		.WORD _obj_anim28_4
		.WORD _obj_anim28_5
_obj_anim29:
		.WORD _obj_anim28_0
		.WORD _obj_anim28_1
		.WORD _obj_anim28_2
		.WORD _obj_anim28_3
		.WORD _obj_anim29_4
		.WORD _obj_anim29_5
_obj_anim2A:
		.WORD _obj_anim2A_0
		.WORD _obj_anim2A_1
		.WORD _obj_anim2A_2
_obj_anim2B:
		.WORD _obj_anim2B_0
		.WORD _obj_anim2B_1
		.WORD _obj_anim2B_2
_obj_anim2C:
		.WORD _obj_anim2C_0
		.WORD _obj_anim2C_1
		.WORD _obj_anim2C_2
_obj_anim2D:
		.WORD _obj_anim2D_0
		.WORD _obj_anim2D_1
_obj_anim2E:
		.WORD _obj_anim2E_0
		.WORD _obj_anim2E_1
		.WORD _obj_anim2E_2
		.WORD _obj_anim2E_3
_obj_anim2F:
		.WORD _obj_anim2F_0
		.WORD _obj_anim2F_1
		.WORD _obj_anim2F_2
		.WORD _obj_anim2F_3
_obj_anim30:
		.WORD _obj_anim30_0
		.WORD _obj_anim30_1
_obj_anim31:
		.WORD _obj_anim31_0
		.WORD _obj_anim31_1
_obj_anim32:
		.WORD _obj_anim32_0
		.WORD _obj_anim32_1
		.WORD _obj_anim32_2
_obj_anim33:
		.WORD _obj_anim33_0
		.WORD _obj_anim33_1
		.WORD _obj_anim33_2
		.WORD _obj_anim33_3
_obj_anim34:
		.WORD _obj_anim34_0
		.WORD _obj_anim34_1
		.WORD _obj_anim34_2
		.WORD _obj_anim34_3
_obj_anim35:
		.WORD _obj_anim35_0
		.WORD _obj_anim35_1
_obj_anim36:
		.WORD _obj_anim36_0
		.WORD _obj_anim36_1
_obj_anim37:
		.WORD _obj_anim37_0
		.WORD _obj_anim37_1
		.WORD _obj_anim37_2
_obj_anim38:
		.WORD _obj_anim38_0
		.WORD _obj_anim38_1
_obj_anim39:
		.WORD _obj_anim39_0
		.WORD _obj_anim39_1
		.WORD _obj_anim39_2
_obj_anim3A:
		.WORD _obj_anim3A_0
		.WORD _obj_anim3A_1
		.WORD _obj_anim3A_2
_obj_anim3B:
		.WORD _obj_anim3B_0
		.WORD _obj_anim3B_1
		.WORD _obj_anim3B_2
_obj_anim3C:
		.WORD _obj_anim3C_0
		.WORD _obj_anim3C_1
_obj_anim3D:
		.WORD _obj_anim3D_0
		.WORD _obj_anim3D_1
_obj_anim3E:
		.WORD _obj_anim3D_0
		.WORD _obj_anim3D_1
		.WORD _obj_anim3E_2
_obj_anim3F:
		.WORD _obj_anim3F_0
		.WORD _obj_anim3F_1
		.WORD _obj_anim3F_2
		.WORD _obj_anim3F_3
		.WORD _obj_anim3F_4
		.WORD _obj_anim3F_5
		.WORD _obj_anim3F_6
_obj_anim00_0:
		.BYTE $07,$00,$04
_obj_anim00_1:
		.BYTE $1B,$01,$01,$02,$02,$03,$03,$04
_obj_anim00_2:
		.BYTE $0F,$02,$03,$01,$04
_obj_anim00_3:
		.BYTE $07,$04,$04
_obj_anim00_4:
		.BYTE $07,$4E,$04
_obj_anim00_5:
		.BYTE $13,$01,$02,$02,$03,$10
_obj_anim00_6:
		.BYTE $07,$04,$04
_obj_anim00_7:
		.BYTE $0F,$0D,$0E,$00,$0C
_obj_anim00_8:
		.BYTE $0F,$0F,$10,$04,$0C
_obj_anim00_9:
		.BYTE $0F,$07,$07,$00,$0C
_obj_anim00_A:
		.BYTE $0F,$08,$08,$04,$0C
_obj_anim00_B:
		.BYTE $0F,$05,$05,$00,$0C
_obj_anim00_C:
		.BYTE $0F,$06,$06,$04,$0C
_obj_anim00_D:
		.BYTE $0F,$09,$0A,$00,$0C
_obj_anim00_E:
		.BYTE $0F,$0B,$0C,$04,$0C
_obj_anim01_0:
		.BYTE $07,$11,$04
_obj_anim01_1:
		.BYTE $13,$11,$11,$12,$12,$04
_obj_anim02_0:
		.BYTE $07,$13,$04
_obj_anim02_1:
		.BYTE $13,$13,$13,$14,$14,$04
_obj_anim03_0:
		.BYTE $07,$15,$04
_obj_anim03_1:
		.BYTE $13,$15,$15,$16,$16,$04
_obj_anim03_2:
		.BYTE $07,$CB,$04
_obj_anim03_3:
		.BYTE $07,$CC,$04
_obj_anim04_0:
		.BYTE $07,$17,$04
_obj_anim04_1:
		.BYTE $13,$17,$17,$18,$18,$04
_obj_anim05_0:
		.BYTE $0B,$19,$1A,$04
_obj_anim06_0:
		.BYTE $07,$1C,$04
_obj_anim06_1:
		.BYTE $13,$1C,$1C,$1B,$1B,$04
_obj_anim07_0:
		.BYTE $13,$1D,$1D,$1D,$1E,$04
_obj_anim08_0:
		.BYTE $07,$1F,$04
_obj_anim09_0:
		.BYTE $07,$20,$04
_obj_anim09_1:
		.BYTE $13,$20,$20,$20,$21,$04
_obj_anim0A_0:
		.BYTE $07,$22,$04
_obj_anim0B_0:
		.BYTE $07,$23,$04
_obj_anim0C_0:
		.BYTE $13,$24,$24,$25,$25,$04
_obj_anim0C_1:
		.BYTE $07,$25,$04
_obj_anim0D_0:
		.BYTE $07,$26,$04
_obj_anim0E_0:
		.BYTE $0B,$27,$28,$04
_obj_anim0F_0:
		.BYTE $07,$29,$04
_obj_anim10_0:
		.BYTE $07,$2A,$04
_obj_anim10_1:
		.BYTE $07,$2B,$04
_obj_anim11_0:
		.BYTE $07,$2C,$04
_obj_anim12_0:
		.BYTE $07,$2D,$04
_obj_anim12_1:
		.BYTE $07,$2E,$04
_obj_anim13_0:
		.BYTE $07,$2F,$04
_obj_anim13_1:
		.BYTE $07,$30,$04
_obj_anim14_1:
		.BYTE $13,$31,$31,$32,$32,$04
_obj_anim15_0:
		.BYTE $07,$33,$04
_obj_anim16_0:
		.BYTE $13,$34,$35,$36,$37,$10
_obj_anim16_1:
		.BYTE $1F,$34,$35,$36,$37,$38,$3A,$38,$1C
_obj_anim16_2:
		.BYTE $23,$34,$35,$36,$37,$38,$39,$3B,$39,$20
_obj_anim16_3:
		.BYTE $13,$37,$36,$35,$34,$10
_obj_anim16_4:
		.BYTE $17,$38,$37,$36,$35,$34,$14
_obj_anim16_5:
		.BYTE $1B,$39,$38,$37,$36,$35,$34,$18
_obj_anim17_0:
		.BYTE $07,$3D,$04
_obj_anim17_1:
		.BYTE $13,$3C,$3C,$3D,$3D,$04
_obj_anim17_2:
		.BYTE $13,$3E,$3E,$3F,$3F,$04
_obj_anim18_0:
		.BYTE $07,$42,$04
_obj_anim18_1:
		.BYTE $13,$40,$40,$41,$41,$04
_obj_anim18_2:
		.BYTE $07,$43,$04
_obj_anim19_0:
		.BYTE $07,$44,$04
_obj_anim19_1:
		.BYTE $0F,$47,$45,$46,$0C
_obj_anim1A_0:
		.BYTE $07,$48,$04
_obj_anim1A_1:
		.BYTE $0F,$4B,$49,$4A,$0C
_obj_anim1B_0:
		.BYTE $13,$4C,$4C,$4D,$4D,$04
_obj_anim1C_0:
		.BYTE $1B,$4F,$4F,$50,$50,$51,$51,$04
_obj_anim1C_1:
		.BYTE $0F,$4F,$50,$51,$04
_obj_anim1C_2:
		.BYTE $07,$52,$04
_obj_anim1C_3:
		.BYTE $13,$50,$50,$50,$51,$10
_obj_anim1C_4:
		.BYTE $07,$53,$04
_obj_anim1D_4:
		.BYTE $07,$54,$04
_obj_anim1E_4:
		.BYTE $07,$55,$04
_obj_anim1F_4:
		.BYTE $07,$56,$04
_obj_anim20_0:
		.BYTE $07,$64,$04
_obj_anim20_1:
		.BYTE $1B,$5D,$5D,$5E,$5E,$5F,$5F,$04
_obj_anim21_0:
		.BYTE $1B,$57,$57,$58,$58,$59,$59,$04
_obj_anim21_1:
		.BYTE $0F,$57,$58,$59,$04
_obj_anim21_2:
		.BYTE $07,$5A,$04
_obj_anim21_3:
		.BYTE $13,$58,$58,$58,$59,$10
_obj_anim21_4:
		.BYTE $07,$5B,$04
_obj_anim22_4:
		.BYTE $07,$5C,$04
_obj_anim23_0:
		.BYTE $1B,$5D,$5D,$5E,$5E,$5F,$5F,$04
_obj_anim23_1:
		.BYTE $0F,$5D,$5E,$5F,$04
_obj_anim23_2:
		.BYTE $07,$60,$04
_obj_anim23_3:
		.BYTE $13,$5E,$5E,$5E,$5F,$10
_obj_anim23_4:
		.BYTE $0F,$61,$61,$5E,$0C
_obj_anim24_4:
		.BYTE $07,$62,$04
_obj_anim25_4:
		.BYTE $07,$63,$04
_obj_anim26_4:
		.BYTE $13,$64,$65,$65,$64,$10
_obj_anim27_4:
		.BYTE $07,$66,$04
_obj_anim28_0:
		.BYTE $1B,$67,$67,$68,$68,$69,$69,$04
_obj_anim28_1:
		.BYTE $0F,$67,$68,$69,$04
_obj_anim28_2:
		.BYTE $07,$6A,$04
_obj_anim28_3:
		.BYTE $13,$68,$68,$68,$69,$10
_obj_anim28_4:
		.BYTE $07,$6C,$04
_obj_anim28_5:
		.BYTE $07,$6E,$04
_obj_anim29_4:
		.BYTE $07,$6B,$04
_obj_anim29_5:
		.BYTE $07,$6D,$04
_obj_anim2A_0:
		.BYTE $07,$6F,$04
_obj_anim2A_1:
		.BYTE $13,$70,$70,$71,$71,$04
_obj_anim2A_2:
		.BYTE $13,$72,$72,$73,$73,$04
_obj_anim2B_0:
		.BYTE $07,$74,$04
_obj_anim2B_1:
		.BYTE $13,$75,$75,$76,$76,$04
_obj_anim2B_2:
		.BYTE $13,$77,$77,$78,$78,$04
_obj_anim2C_0:
		.BYTE $07,$79,$04
_obj_anim2C_1:
		.BYTE $13,$79,$79,$7A,$7A,$04
_obj_anim2C_2:
		.BYTE $0F,$7B,$7B,$79,$0C
_obj_anim2D_0:
		.BYTE $0B,$7C,$7D,$04
_obj_anim2D_1:
		.BYTE $13,$7E,$7E,$7E,$7D,$10
_obj_anim2E_0:
		.BYTE $07,$7F,$04
_obj_anim2E_1:
		.BYTE $13,$7F,$7F,$80,$80,$04
_obj_anim2E_2:
		.BYTE $13,$81,$81,$82,$82,$04
_obj_anim2E_3:
		.BYTE $07,$83,$04
_obj_anim2F_0:
		.BYTE $07,$84,$04
_obj_anim2F_1:
		.BYTE $0F,$85,$85,$84,$0C
_obj_anim2F_2:
		.BYTE $0F,$86,$86,$84,$0C
_obj_anim2F_3:
		.BYTE $0F,$87,$87,$84,$0C
_obj_anim30_0:
		.BYTE $07,$88,$04
_obj_anim30_1:
		.BYTE $13,$8A,$8A,$8A,$89,$10
_obj_anim31_0:
		.BYTE $07,$8B,$04
_obj_anim31_1:
		.BYTE $13,$8C,$8C,$8C,$8B,$10
_obj_anim32_0:
		.BYTE $07,$8D,$04
_obj_anim32_1:
		.BYTE $13,$8D,$8D,$8E,$8E,$04
_obj_anim32_2:
		.BYTE $13,$8F,$8F,$8F,$8E,$10
_obj_anim33_0:
		.BYTE $07,$91,$04
_obj_anim33_1:
		.BYTE $0B,$90,$91,$04
_obj_anim33_2:
		.BYTE $07,$92,$04
_obj_anim33_3:
		.BYTE $0F,$93,$93,$91,$0C
_obj_anim34_0:
		.BYTE $07,$94,$04
_obj_anim34_1:
		.BYTE $0F,$95,$95,$94,$0C
_obj_anim34_2:
		.BYTE $07,$96,$04
_obj_anim34_3:
		.BYTE $0F,$97,$97,$96,$0C
_obj_anim35_0:
		.BYTE $1B,$94,$94,$94,$94,$95,$95,$04
_obj_anim35_1:
		.BYTE $1B,$96,$96,$96,$96,$97,$97,$04
_obj_anim36_0:
		.BYTE $07,$9A,$04
_obj_anim36_1:
		.BYTE $0F,$99,$9B,$98,$0C
_obj_anim37_0:
		.BYTE $13,$9C,$9C,$9D,$9D,$04
_obj_anim37_1:
		.BYTE $13,$9E,$9C,$9C,$9D,$10
_obj_anim37_2:
		.BYTE $07,$9F,$04
_obj_anim38_0:
		.BYTE $07,$A0,$04
_obj_anim38_1:
		.BYTE $07,$A1,$04
_obj_anim39_0:
		.BYTE $07,$A3,$04
_obj_anim39_1:
		.BYTE $1F,$A2,$A2,$A4,$A4,$A2,$A2,$A3,$1C
_obj_anim39_2:
		.BYTE $07,$A5,$04
_obj_anim3A_0:
		.BYTE $23,$BC,$BC,$BD,$BD,$BC,$BC,$BE,$BE,$04
_obj_anim3A_1:
		.BYTE $07,$BF,$04
_obj_anim3A_2:
		.BYTE $07,$C0,$04
_obj_anim3B_0:
		.BYTE $23,$C1,$C1,$C2,$C2,$C1,$C1,$C3,$C3,$04
_obj_anim3B_1:
		.BYTE $07,$C4,$04
_obj_anim3B_2:
		.BYTE $07,$C5,$04
_obj_anim3C_0:
		.BYTE $07,$C6,$04
_obj_anim3C_1:
		.BYTE $1F,$C7,$C7,$C7,$C8,$C8,$C8,$C9,$1C
_obj_anim3E_2:
		.BYTE $0B,$AA,$AB,$04
_obj_anim3D_0:
		.BYTE $0B,$AC,$A6,$04
_obj_anim3D_1:
		.BYTE $0B,$AD,$A7,$04
_obj_anim3F_0:
		.BYTE $07,$CA,$04
_obj_anim3F_1:
		.BYTE $0F,$AE,$AF,$AE,$0C
_obj_anim3F_2:
		.BYTE $13,$B0,$B1,$B2,$B3,$10
_obj_anim3F_3:
		.BYTE $13,$B4,$B5,$B6,$B7,$10
_obj_anim3F_4:
		.BYTE $13,$B8,$B9,$BA,$BB,$10
_obj_anim3F_5:
		.BYTE $07,$A9,$04
_obj_anim3F_6:
		.BYTE $07,$A8,$04
_spr_libA:
		.WORD _spr00
		.WORD _spr01
		.WORD _spr02
		.WORD _spr03
		.WORD _spr04
		.WORD _spr05
		.WORD _spr06
		.WORD _spr07
		.WORD _spr08
		.WORD _spr09
		.WORD _spr0A
		.WORD _spr0B
		.WORD _spr0C
		.WORD _spr0D
		.WORD _spr0E
		.WORD _spr0F
		.WORD _spr10
		.WORD _spr11
		.WORD _spr12
		.WORD _spr13
		.WORD _spr14
		.WORD _spr15
		.WORD _spr16
		.WORD _spr17
		.WORD _spr18
		.WORD _spr19
		.WORD _spr1A
		.WORD _spr1B
		.WORD _spr1C
		.WORD _spr1D
		.WORD _spr1E
		.WORD _spr1F
		.WORD _spr20
		.WORD _spr21
		.WORD _spr22
		.WORD _spr23
		.WORD _spr24
		.WORD _spr25
		.WORD _spr26
		.WORD _spr27
		.WORD _spr28
		.WORD _spr29
		.WORD _spr2A
		.WORD _spr2B
		.WORD _spr2C
		.WORD _spr2D
		.WORD _spr2E
		.WORD _spr2F
		.WORD _spr30
		.WORD _spr31
		.WORD _spr32
		.WORD _spr33
		.WORD _spr34
		.WORD _spr35
		.WORD _spr36
		.WORD _spr37
		.WORD _spr38
		.WORD _spr39
		.WORD _spr3A
		.WORD _spr3B
		.WORD _spr3C
		.WORD _spr3D
		.WORD _spr3E
		.WORD _spr3F
		.WORD _spr40
		.WORD _spr41
		.WORD _spr42
		.WORD _spr43
		.WORD _spr44
		.WORD _spr45
		.WORD _spr46
		.WORD _spr47
		.WORD _spr48
		.WORD _spr49
		.WORD _spr4A
		.WORD _spr4B
		.WORD _spr4C
		.WORD _spr4D
		.WORD _spr4E
		.WORD _spr4F
		.WORD _spr50
		.WORD _spr51
		.WORD _spr52
		.WORD _spr53
		.WORD _spr54
		.WORD _spr55
		.WORD _spr56
		.WORD _spr57
		.WORD _spr58
		.WORD _spr59
		.WORD _spr5A
		.WORD _spr5B
		.WORD _spr5C
		.WORD _spr5D
		.WORD _spr5E
		.WORD _spr5F
		.WORD _spr60
		.WORD _spr61
		.WORD _spr62
		.WORD _spr63
		.WORD _spr64
		.WORD _spr65
		.WORD _spr66
		.WORD _spr67
		.WORD _spr68
		.WORD _spr69
		.WORD _spr6A
		.WORD _spr6B
		.WORD _spr6C
		.WORD _spr6D
		.WORD _spr6E
		.WORD _spr6F
		.WORD _spr70
		.WORD _spr71
		.WORD _spr72
		.WORD _spr73
		.WORD _spr74
		.WORD _spr75
		.WORD _spr76
		.WORD _spr77
		.WORD _spr78
		.WORD _spr79
		.WORD _spr7A
		.WORD _spr7B
		.WORD _spr7C
		.WORD _spr7D
		.WORD _spr7E
		.WORD _spr7F
_spr_libB:
		.WORD _spr80
		.WORD _spr81
		.WORD _spr82
		.WORD _spr83
		.WORD _spr84
		.WORD _spr85
		.WORD _spr86
		.WORD _spr87
		.WORD _spr88
		.WORD _spr89
		.WORD _spr8A
		.WORD _spr8B
		.WORD _spr8C
		.WORD _spr8D
		.WORD _spr8E
		.WORD _spr8F
		.WORD _spr90
		.WORD _spr91
		.WORD _spr92
		.WORD _spr93
		.WORD _spr94
		.WORD _spr95
		.WORD _spr96
		.WORD _spr97
		.WORD _spr98
		.WORD _spr99
		.WORD _spr9A
		.WORD _spr9B
		.WORD _spr9C
		.WORD _spr9D
		.WORD _spr9E
		.WORD _spr9F
		.WORD _sprA0
		.WORD _sprA1
		.WORD _sprA2
		.WORD _sprA3
		.WORD _sprA4
		.WORD _sprA5
		.WORD _sprA6
		.WORD _sprA7
		.WORD _sprA8
		.WORD _sprA9
		.WORD _sprAA
		.WORD _sprAB
		.WORD _sprAC
		.WORD _sprAD
		.WORD _sprAE
		.WORD _sprAF
		.WORD _sprB0
		.WORD _sprB1
		.WORD _sprB2
		.WORD _sprB3
		.WORD _sprB4
		.WORD _sprB5
		.WORD _sprB6
		.WORD _sprB7
		.WORD _sprB8
		.WORD _sprB9
		.WORD _sprBA
		.WORD _sprBB
		.WORD _sprBC
		.WORD _sprBD
		.WORD _sprBE
		.WORD _sprBF
		.WORD _sprC0
		.WORD _sprC1
		.WORD _sprC2
		.WORD _sprC3
		.WORD _sprC4
		.WORD _sprC5
		.WORD _sprC6
		.WORD _sprC7
		.WORD _sprC8
		.WORD _sprC9
		.WORD _sprCA
		.WORD _sprCB
		.WORD _sprCC
_spr00:
		.BYTE $00,$66,$64,$62,$60,$40,$FF
_spr01:
		.BYTE $00,$44,$56,$46,$54,$40,$FF
_spr02:
		.BYTE $00,$5A,$4A,$58,$48,$40,$FF
_spr03:
		.BYTE $00,$6A,$52,$42,$50,$40,$FF
_spr04:
		.BYTE $00,$68,$48,$40,$FF
_spr05:
		.BYTE $00,$BD,$BA,$75,$B2,$70,$FF
_spr06:
		.BYTE $00,$68,$B7,$70,$FF
_spr07:
		.BYTE $00,$BD,$AD,$B6,$B3,$B0,$FF
_spr08:
		.BYTE $00,$B9,$B3,$B0,$FF
_spr09:
		.BYTE $00,$BD,$AD,$76,$7A,$78,$FF
_spr0A:
		.BYTE $00,$BD,$AD,$76,$B2,$70,$FF
_spr0B:
		.BYTE $00,$68,$7A,$78,$FF
_spr0C:
		.BYTE $00,$68,$B2,$70,$FF
_spr0D:
		.BYTE $00,$BD,$AD,$76,$7A,$78,$3C,$FF
_spr0E:
		.BYTE $00,$BD,$AD,$76,$F2,$70,$FF
_spr0F:
		.BYTE $00,$68,$7A,$78,$3C,$FF
_spr10:
		.BYTE $00,$68,$F2,$70,$FF
_spr11:
		.BYTE $40,$48,$46,$44,$42,$40,$FF
_spr12:
		.BYTE $40,$4E,$4C,$4A,$42,$40,$FF
_spr13:
		.BYTE $50,$48,$46,$44,$42,$40,$FF
_spr14:
		.BYTE $50,$4E,$4C,$4A,$42,$40,$FF
_spr15:
		.BYTE $61,$48,$46,$44,$42,$40,$FF
_spr16:
		.BYTE $61,$4E,$4C,$4A,$42,$40,$FF
_spr17:
		.BYTE $71,$48,$46,$44,$42,$40,$FF
_spr18:
		.BYTE $71,$4E,$4C,$4A,$42,$40,$FF
_spr19:
		.BYTE $80,$42,$40,$FF
_spr1A:
		.BYTE $80,$46,$44,$FF
_spr1B:
		.BYTE $80,$8B,$88,$FF
_spr1C:
		.BYTE $80,$4E,$49,$FF
_spr1D:
		.BYTE $90,$42,$40,$FF
_spr1E:
		.BYTE $90,$46,$44,$FF
_spr1F:
		.BYTE $80,$0C,$FF
_spr20:
		.BYTE $81,$42,$40,$FF
_spr21:
		.BYTE $81,$46,$44,$FF
_spr22:
		.BYTE $82,$4E,$4C,$FF
_spr23:
		.BYTE $81,$4A,$48,$FF
_spr24:
		.BYTE $90,$42,$40,$FF
_spr25:
		.BYTE $90,$46,$44,$FF
_spr26:
		.BYTE $90,$CC,$C8,$FF
_spr27:
		.BYTE $91,$40,$FF
_spr28:
		.BYTE $91,$42,$FF
_spr29:
		.BYTE $92,$04,$FF
_spr2A:
		.BYTE $80,$42,$40,$FF
_spr2B:
		.BYTE $80,$46,$44,$FF
_spr2C:
		.BYTE $80,$4E,$FF
_spr2D:
		.BYTE $90,$42,$40,$FF
_spr2E:
		.BYTE $90,$46,$44,$FF
_spr2F:
		.BYTE $90,$4A,$48,$FF
_spr30:
		.BYTE $90,$4E,$4C,$FF
_spr31:
		.BYTE $90,$4A,$48,$FF
_spr32:
		.BYTE $90,$4E,$4C,$FF
_spr33:
		.BYTE $80,$0F,$0E,$FF
_spr34:
		.BYTE $92,$0E,$0D,$47,$45,$FF
_spr35:
		.BYTE $92,$0E,$0D,$0E,$0D,$47,$45,$FF
_spr36:
		.BYTE $92,$0E,$0D,$0E,$0D,$0E,$0D,$47,$45,$FF
_spr37:
		.BYTE $92,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$47,$45,$FF
_spr38:
		.BYTE $92,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$47,$45,$FF
_spr39:
		.BYTE $92,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$47,$45,$FF
_spr3A:
		.BYTE $92,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$4B,$49,$FF
_spr3B:
		.BYTE $92,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$0E,$0D,$4B,$49,$FF
_spr3C:
		.BYTE $82,$44,$48,$42,$40,$FF
_spr3D:
		.BYTE $82,$46,$48,$42,$40,$FF
_spr3E:
		.BYTE $82,$44,$C8,$FF
_spr3F:
		.BYTE $82,$46,$C8,$FF
_spr40:
		.BYTE $60,$4B,$9D,$8D,$FF
_spr41:
		.BYTE $60,$5B,$9D,$8D,$FF
_spr42:
		.BYTE $60,$98,$88,$94,$FF
_spr43:
		.BYTE $60,$C4,$D0,$C0,$FF
_spr44:
		.BYTE $40,$D4,$C4,$FF
_spr45:
		.BYTE $40,$D8,$C8,$FF
_spr46:
		.BYTE $40,$DC,$CC,$FF
_spr47:
		.BYTE $40,$D0,$C0,$FF
_spr48:
		.BYTE $62,$D4,$C4,$FF
_spr49:
		.BYTE $62,$D8,$C8,$FF
_spr4A:
		.BYTE $62,$DC,$CC,$FF
_spr4B:
		.BYTE $62,$D0,$C0,$FF
_spr4C:
		.BYTE $50,$0B,$0C,$0A,$FF
_spr4D:
		.BYTE $50,$0D,$0C,$0A,$FF
_spr4E:
		.BYTE $00,$5E,$4E,$5C,$4C,$FF
_spr4F:
		.BYTE $A1,$44,$56,$46,$54,$40,$FF
_spr50:
		.BYTE $A1,$5A,$4A,$58,$48,$40,$FF
_spr51:
		.BYTE $A1,$5E,$52,$42,$50,$40,$FF
_spr52:
		.BYTE $A1,$44,$4E,$5C,$4C,$FF
_spr53:
		.BYTE $A1,$69,$E5,$A2,$60,$FF
_spr54:
		.BYTE $A1,$BA,$B7,$75,$B2,$70,$FF
_spr55:
		.BYTE $A1,$A9,$A6,$AC,$60,$FF
_spr56:
		.BYTE $A1,$A9,$A6,$A3,$60,$FF
_spr57:
		.BYTE $A2,$44,$56,$46,$54,$40,$FF
_spr58:
		.BYTE $A2,$5A,$4A,$58,$48,$40,$FF
_spr59:
		.BYTE $A2,$5E,$52,$42,$50,$40,$FF
_spr5A:
		.BYTE $A2,$44,$4E,$5C,$4C,$FF
_spr5B:
		.BYTE $A2,$69,$E5,$A2,$60,$FF
_spr5C:
		.BYTE $A2,$BA,$B7,$75,$B2,$70,$FF
_spr5D:
		.BYTE $A1,$44,$56,$46,$54,$40,$FF
_spr5E:
		.BYTE $A1,$5A,$4A,$58,$48,$40,$FF
_spr5F:
		.BYTE $A1,$5E,$52,$42,$50,$40,$FF
_spr60:
		.BYTE $A1,$44,$4E,$5C,$4C,$FF
_spr61:
		.BYTE $A1,$6B,$69,$E5,$A2,$60,$FF
_spr62:
		.BYTE $A1,$79,$77,$75,$B2,$70,$FF
_spr63:
		.BYTE $A1,$AA,$A7,$65,$A2,$60,$FF
_spr64:
		.BYTE $A1,$68,$66,$64,$62,$60,$FF
_spr65:
		.BYTE $A1,$68,$66,$6D,$AA,$60,$FF
_spr66:
		.BYTE $A1,$B9,$B6,$B3,$B0,$FF
_spr67:
		.BYTE $A2,$44,$56,$46,$54,$40,$FF
_spr68:
		.BYTE $A2,$5A,$4A,$58,$48,$40,$FF
_spr69:
		.BYTE $A2,$5E,$52,$42,$50,$40,$FF
_spr6A:
		.BYTE $A2,$44,$4E,$5C,$4C,$FF
_spr6B:
		.BYTE $A2,$79,$77,$75,$B2,$70,$FF
_spr6C:
		.BYTE $A2,$AA,$A7,$65,$A2,$60,$FF
_spr6D:
		.BYTE $A2,$7B,$BD,$6D,$FF
_spr6E:
		.BYTE $A2,$7B,$A2,$60,$FF
_spr6F:
		.BYTE $A1,$44,$52,$42,$50,$40,$FF
_spr70:
		.BYTE $A1,$56,$46,$42,$50,$40,$FF
_spr71:
		.BYTE $A1,$4D,$4B,$42,$50,$40,$FF
_spr72:
		.BYTE $A1,$56,$46,$58,$88,$40,$FF
_spr73:
		.BYTE $A1,$4D,$4B,$58,$88,$40,$FF
_spr74:
		.BYTE $C1,$48,$46,$44,$42,$40,$FF
_spr75:
		.BYTE $C1,$4E,$4C,$4A,$42,$40,$FF
_spr76:
		.BYTE $C1,$57,$55,$4A,$42,$40,$FF
_spr77:
		.BYTE $C1,$4E,$4C,$53,$90,$40,$FF
_spr78:
		.BYTE $C1,$57,$55,$53,$90,$40,$FF
_spr79:
		.BYTE $48,$53,$43,$50,$40,$FF
_spr7A:
		.BYTE $48,$56,$46,$50,$40,$FF
_spr7B:
		.BYTE $48,$4C,$49,$99,$3E,$FF
_spr7C:
		.BYTE $62,$83,$90,$80,$FF
_spr7D:
		.BYTE $62,$9C,$8C,$99,$FF
_spr7E:
		.BYTE $60,$89,$96,$86,$93,$FF
_spr7F:
		.BYTE $41,$45,$52,$5A,$4A,$40,$FF
_spr80:
		.BYTE $41,$58,$48,$5C,$4C,$40,$FF
_spr81:
		.BYTE $41,$45,$52,$82,$50,$40,$FF
_spr82:
		.BYTE $41,$58,$48,$95,$50,$40,$FF
_spr83:
		.BYTE $41,$45,$52,$5E,$4E,$40,$FF
_spr84:
		.BYTE $60,$54,$44,$52,$42,$50,$40,$FF
_spr85:
		.BYTE $60,$54,$44,$52,$96,$46,$40,$FF
_spr86:
		.BYTE $60,$54,$44,$52,$4D,$9C,$40,$FF
_spr87:
		.BYTE $60,$0B,$99,$88,$42,$50,$40,$FF
_spr88:
		.BYTE $80,$44,$52,$42,$50,$40,$FF
_spr89:
		.BYTE $80,$58,$48,$56,$46,$54,$FF
_spr8A:
		.BYTE $80,$4E,$5C,$4C,$5A,$4A,$FF
_spr8B:
		.BYTE $60,$86,$93,$83,$90,$80,$FF
_spr8C:
		.BYTE $60,$9C,$8C,$99,$89,$96,$FF
_spr8D:
		.BYTE $40,$83,$90,$80,$FF
_spr8E:
		.BYTE $40,$96,$86,$93,$FF
_spr8F:
		.BYTE $40,$9C,$8C,$99,$89,$FF
_spr90:
		.BYTE $40,$52,$42,$50,$40,$FF
_spr91:
		.BYTE $40,$56,$46,$54,$44,$FF
_spr92:
		.BYTE $40,$4A,$58,$48,$FF
_spr93:
		.BYTE $40,$5E,$4E,$9A,$4C,$FF
_spr94:
		.BYTE $60,$44,$52,$42,$50,$40,$FF
_spr95:
		.BYTE $60,$58,$48,$56,$46,$54,$FF
_spr96:
		.BYTE $60,$5E,$4E,$5C,$FF
_spr97:
		.BYTE $60,$4C,$5A,$4A,$FF
_spr98:
		.BYTE $A0,$D4,$C4,$FF
_spr99:
		.BYTE $A0,$D8,$C8,$FF
_spr9A:
		.BYTE $A0,$DC,$CC,$FF
_spr9B:
		.BYTE $A0,$D0,$C0,$FF
_spr9C:
		.BYTE $C8,$B8,$B8,$A6,$A0,$FF
_spr9D:
		.BYTE $C8,$B8,$B8,$B2,$AC,$FF
_spr9E:
		.BYTE $C8,$B8,$A6,$A0,$FF
_spr9F:
		.BYTE $C0,$5E,$FF
_sprA0:
		.BYTE $8A,$94,$83,$70,$40,$FF
_sprA1:
		.BYTE $82,$4E,$9D,$D9,$C8,$4C,$FF
_sprA2:
		.BYTE $82,$D4,$84,$90,$C0,$FF
_sprA3:
		.BYTE $82,$D4,$98,$88,$C0,$FF
_sprA4:
		.BYTE $82,$D4,$9B,$8B,$C0,$FF
_sprA5:
		.BYTE $80,$5E,$4E,$FF
_sprA6:
		.BYTE $92,$DA,$D6,$D2,$EC,$FF
_sprA7:
		.BYTE $92,$6A,$E6,$E2,$F0,$FF
_sprA8:
		.BYTE $C3,$DC,$CC,$C4,$C8,$FF
_sprA9:
		.BYTE $80,$4A,$48,$FF
_sprAA:
		.BYTE $89,$B0,$A7,$A0,$FF
_sprAB:
		.BYTE $89,$B0,$A7,$B7,$FF
_sprAC:
		.BYTE $92,$DA,$D6,$D2,$CE,$FF
_sprAD:
		.BYTE $92,$6A,$E6,$E2,$DE,$FF
_sprAE:
		.BYTE $E3,$1B,$FF
_sprAF:
		.BYTE $E3,$1C,$FF
_sprB0:
		.BYTE $E3,$1B,$FF
_sprB1:
		.BYTE $E3,$5C,$5B,$FF
_sprB2:
		.BYTE $E3,$5B,$5C,$FF
_sprB3:
		.BYTE $E3,$1D,$FF
_sprB4:
		.BYTE $E3,$5C,$5B,$5C,$1D,$FF
_sprB5:
		.BYTE $E3,$5B,$5C,$1B,$FF
_sprB6:
		.BYTE $E3,$5C,$1D,$FF
_sprB7:
		.BYTE $E3,$1B,$FF
_sprB8:
		.BYTE $E3,$5C,$9B,$5C,$9B,$FF
_sprB9:
		.BYTE $E3,$9B,$5C,$9B,$FF
_sprBA:
		.BYTE $E3,$5C,$9B,$FF
_sprBB:
		.BYTE $E3,$1B,$FF
_sprBC:
		.BYTE $A2,$45,$53,$43,$51,$41,$FF
_sprBD:
		.BYTE $A2,$5B,$4B,$59,$49,$41,$FF
_sprBE:
		.BYTE $A2,$5B,$57,$47,$55,$41,$FF
_sprBF:
		.BYTE $A2,$34,$72,$70,$E0,$80,$FF
_sprC0:
		.BYTE $A2,$B5,$A5,$B8,$E8,$FC,$AC,$9D,$8D,$FF
_sprC1:
		.BYTE $42,$44,$52,$42,$50,$40,$FF
_sprC2:
		.BYTE $42,$5A,$4A,$58,$48,$40,$FF
_sprC3:
		.BYTE $42,$5A,$56,$46,$54,$40,$FF
_sprC4:
		.BYTE $42,$64,$73,$62,$B0,$60,$FF
_sprC5:
		.BYTE $42,$B6,$A6,$B9,$A9,$FC,$AC,$9C,$8C,$FF
_sprC6:
		.BYTE $68,$B0,$A0,$FF
_sprC7:
		.BYTE $60,$0F,$FF
_sprC8:
		.BYTE $60,$1F,$1E,$0E,$FF
_sprC9:
		.BYTE $60,$9B,$8B,$98,$88,$FF
_sprCA:
		.BYTE $20,$0C,$FF
_sprCB:
		.BYTE $C0,$90,$93,$FF
_sprCC:
		.BYTE $C0,$99,$96,$93,$FF
_spr_prize_tile_lib:
		.WORD _spr_prize_tile00
		.WORD _spr_prize_tile01
		.WORD _spr_prize_tile02
		.WORD _spr_prize_tile03
		.WORD _spr_prize_tile04
		.WORD _spr_prize_tile05
		.WORD _spr_prize_tile06
		.WORD _spr_prize_tile07
		.WORD _spr_prize_tile08
		.WORD _spr_prize_tile09
		.WORD _spr_prize_tile0a
		.WORD _spr_prize_tile0b
		.WORD _spr_prize_tile0c
		.WORD _spr_prize_tile0d
		.WORD _spr_prize_tile0e
		.WORD _spr_prize_tile0f
		.WORD _spr_prize_tile10
		.WORD _spr_prize_tile11
		.WORD _spr_prize_tile12
		.WORD _spr_prize_tile13
		.WORD _spr_prize_tile14
		.WORD _spr_prize_tile15
		.WORD _spr_prize_tile16
		.WORD _spr_prize_tile17
		.WORD _spr_prize_tile18
		.WORD _spr_prize_tile19
		.WORD _spr_prize_tile1a
		.WORD _spr_prize_tile1b
		.WORD _spr_prize_tile1c
_spr_prize_tile14:
		.BYTE $EE
_spr_prize_tile15:
		.BYTE $EF
_spr_prize_tile16:
		.BYTE $F8
_spr_prize_tile17:
		.BYTE $6E,$EC
_spr_prize_tile18:
		.BYTE $6F,$EC
_spr_prize_tile19:
		.BYTE $78,$EC
_spr_prize_tile1a:
		.BYTE $6E,$ED
_spr_prize_tile1b:
		.BYTE $6F,$ED
_spr_prize_tile1c:
		.BYTE $78,$ED
_spr_prize_tile0a:
		.BYTE $60,$E1
_spr_prize_tile0b:
		.BYTE $62,$E3
_spr_prize_tile0c:
		.BYTE $64,$E5
_spr_prize_tile0d:
		.BYTE $66,$E7
_spr_prize_tile0e:
		.BYTE $68,$E9
_spr_prize_tile0f:
		.BYTE $EA
_spr_prize_tile10:
		.BYTE $EB
_spr_prize_tile11:
		.BYTE $F9
_spr_prize_tile12:
		.BYTE $FA
_spr_prize_tile13:
		.BYTE $FF
_spr_prize_tile00:
		.BYTE $FF
_spr_prize_tile01:
		.BYTE $F3
_spr_prize_tile02:
		.BYTE $71,$F2
_spr_prize_tile03:
		.BYTE $71,$F2
_spr_prize_tile04:
		.BYTE $F0
_spr_prize_tile05:
		.BYTE $F4
_spr_prize_tile06:
		.BYTE $F5
_spr_prize_tile07:
		.BYTE $F6
_spr_prize_tile08:
		.BYTE $F7
_spr_prize_tile09:
		.BYTE $FF
