;_apu_mus090:
;		.BYTE $00,$48,$00
;		.BYTE $45-$24,$0C,$09
;		.BYTE $47-$24,$0C,$09
;		.BYTE $48-$24,$0C,$09
;		.BYTE $4A-$24,$0C,$09
;		.BYTE $4C-$24,$0C,$09
;		.BYTE $4C-$24,$90,$60
;		.BYTE $4D-$24,$0C,$09
;		.BYTE $51-$24,$90,$60
_apu_mus09A:
		.BYTE $45-$24,$0C,$09
		.BYTE $47-$24,$0C,$09
		.BYTE $48-$24,$0C,$09
		.BYTE $47-$24,$0C,$09
		.BYTE $48-$24,$0C,$09
		.BYTE $4A-$24,$0C,$09
		.BYTE $48-$24,$0C,$09
		.BYTE $4A-$24,$0C,$09
		.BYTE $4C-$24,$0C,$09
		.BYTE $4A-$24,$0C,$09
		.BYTE $4C-$24,$0C,$09
		.BYTE $4D-$24,$0C,$09
		.BYTE $51-$24,$90,$60
		.BYTE $FD
_apu_mus09B:
		.BYTE $00,$48,$00
		.BYTE $45-$24,$0C,$09
		.BYTE $47-$24,$0C,$09
		.BYTE $48-$24,$0C,$09
		.BYTE $47-$24,$0C,$09
		.BYTE $48-$24,$0C,$09
		.BYTE $4A-$24,$0C,$09
		.BYTE $4C-$24,$90,$60
		.BYTE $FD
_apu_mus09C:
		.BYTE $2D-$18,$24,$18
		.BYTE $2F-$18,$24,$18
		.BYTE $30-$18,$24,$18
		.BYTE $32-$18,$18,$12
		.BYTE $30-$18,$0C,$09
		.BYTE $2D-$18,$90,$60
		.BYTE $FD
_apu_mus09D:
		.BYTE $01,$0C
		.BYTE $02,$0C
		.BYTE $01,$0C
		.BYTE $01,$24
		.BYTE $01,$0C
		.BYTE $02,$0C
		.BYTE $00,$0C
		.BYTE $01,$24
		.BYTE $01,$0C
		.BYTE $01,$06
		.BYTE $01,$06
		.BYTE $01,$0C
		.BYTE $01,$0C
		.BYTE $02,$0C
		.BYTE $00,$0C
		.BYTE $03,$48
		.BYTE $FD
