
_0		EQU $50
_1		EQU $51
_2		EQU $52
_3		EQU $53
_4		EQU $54
_5		EQU $55
_6		EQU $56
_7		EQU $57
_8		EQU $58
_9		EQU $59
_A		EQU $5A
_B		EQU $5B
_C		EQU $5C
_D		EQU $5D
_E		EQU $5E
_F		EQU $5F

_G		EQU $60
_H		EQU $61
_I		EQU $62
_J		EQU $63
_K		EQU $64
_L		EQU $65
_M		EQU $66
_N		EQU $67
_O		EQU $68
_P		EQU $69
_Q		EQU $6A
_R		EQU $6B
_S		EQU $6C
_T		EQU $6D
_U		EQU $6E
_V		EQU $6F

_W		EQU $70
_X		EQU $71
_Y		EQU $72
_Z		EQU $73
_a		EQU $74
_b		EQU $75
_c		EQU $76
_d		EQU $77
_e		EQU $78
_f		EQU $79
_g		EQU $7A
_h		EQU $7B
_i		EQU $7C
_j		EQU $7D
_k		EQU $7E
_l		EQU $7F

_m		EQU $80
_n		EQU $81
_o		EQU $82
_p		EQU $83
_q		EQU $84
_r		EQU $85
_s		EQU $86
_t		EQU $87
_u		EQU $88
_v		EQU $89
_w		EQU $8A
_x		EQU $8B
_y		EQU $8C
_z		EQU $8D
_qe 	EQU $8E
_ex		EQU $8F

_ap 	EQU $90

_cop 	EQU $E2
_rig 	EQU $E3
_dot 	EQU $E4
_col 	EQU $E5
_ddt 	EQU $E6
_dsh 	EQU $E7

_dtt 	EQU $EE
_ls		EQU $EF
_rs 	EQU $F0

__		EQU $F1
_eol 	EQU $FF
_eof 	EQU $FF
